import { Injectable } from '@angular/core';
import { Foods } from '../../shared/models/food';

@Injectable({
  providedIn: 'root'
})
export class FoodService {

  constructor() { }

  getAll():Foods[]{
    return[
      {
        id: 1,
        name: 'Bombil',
        price: 160.00,
        cookTime: '20-30',
        favorite: false,
        origin: ['indian'],
        star:4.5,
        imageUrl: '/assets/Food-1.jpg', //https://bombayfreshfish.com/wp-content/uploads/2022/09/crw_1200h_1200a_cc.jpeg
        tags: ['seafood','fish'],
      },
      {
        id: 2,
        name: 'Surmai',
        price: 600.00,
        cookTime: '30-40',
        favorite: false,
        origin: ['indian'],
        star:3.5,
        imageUrl: '/assets/Food-2.jpg',//'https://bombayfreshfish.com/wp-content/uploads/2022/10/Motka-Main.jpg',
        tags: ['seafood', 'fish'],
      },
      {
        id: 3,
        name: 'White-Paplet',
        price: 100,
        cookTime: '10-15',
        favorite: false,
        origin: ['indian'],
        star:4.5,
        imageUrl: '/assets/Food-3.jpg',// 'https://bombayfreshfish.com/wp-content/uploads/2022/09/bangda-3.webp',
        tags: ['seafood','fish'],
      },
      {
        id: 4,
        name: 'Pink-Jinga',
        price: 10,
        cookTime: '10-15',
        favorite: false,
        origin: ['indian'],
        star:4.5,
        imageUrl: '/assets/Food-4.jpg',// 'https://bombayfreshfish.com/wp-content/uploads/2022/09/Pink-prawns1-LR.jpg',
        tags: ['seafood', 'fish'],
      },
      {
        id: 5,
        name: 'Rawas',
        price: 10,
        cookTime: '10-20',
        favorite: false,
        origin: ['indian'],
        star:4.5,
        imageUrl: '/assets/Food-5.jpg', //'https://bombayfreshfish.com/wp-content/uploads/2022/11/Tilapia-Main.jpg',
        tags: ['River', 'fish'],
      },
      {
        id: 6,
        name: 'Mohari Fish',
        price: 10,
        cookTime: '10-20',
        favorite: false,
        origin: ['indian'],
        star:4.5,
        imageUrl: '/assets/Food-6.JPG', //'https://bombayfreshfish.com/wp-content/uploads/2022/10/Rohu-Main.jpg',
        tags: ['Lake', 'fish'],
      },
      {
        id: 7,
        name: 'Chilapi',
        price: 10,
        cookTime: '20-30',
        favorite: false,
        origin: ['indian'],
        star:4.5,
        imageUrl: '/assets/Food-7.jpg', //'https://bombayfreshfish.com/wp-content/uploads/2022/11/sardine-1.jpg',
        tags: ['River', 'fish'],
      },
      {
        id: 8,
        name: 'Kombda',
        price: 180,
        cookTime: '25-34',
        favorite: false,
        origin: ['indian'],
        star:4.5,
        imageUrl:'/assets/Food-8.jpg', //'https://bombayfreshfish.com/wp-content/uploads/2022/10/Bombil-main.jpg',
        tags: ['River', 'fish'],
      },
      {
        id: 9,
        name: 'Rani',
        price: 220,
        cookTime: '25-34',
        favorite: false,
        origin: ['indian'],
        star:4.5,
        imageUrl:'/assets/Food-9.jpg', //'https://bombayfreshfish.com/wp-content/uploads/2022/10/Bombil-main.jpg',
        tags: ['River', 'fish'],
      },
      {
        id: 10,
        name: 'Small wet peeled Shrimps',
        price: 500,
        cookTime: '25-34',
        favorite: false,
        origin: ['indian'],
        star:4.5,
        imageUrl:'/assets/Food-10.jpg', //'https://bombayfreshfish.com/wp-content/uploads/2022/10/Bombil-main.jpg',
        tags: ['River', 'fish'],
      },
      {
        id: 11,
        name: 'Chopda',
        price: 350,
        cookTime: '25-34',
        favorite: false,
        origin: ['indian'],
        star:4.5,
        imageUrl:'/assets/Food-11.jpg', //'https://bombayfreshfish.com/wp-content/uploads/2022/10/Bombil-main.jpg',
        tags: ['River', 'fish'],
      },
      {
        id: 12,
        name: 'Mandeli',
        price: 390,
        cookTime: '25-34',
        favorite: false,
        origin: ['indian'],
        star:4.5,
        imageUrl:'/assets/Food-12.jpg', //'https://bombayfreshfish.com/wp-content/uploads/2022/10/Bombil-main.jpg',
        tags: ['River', 'fish'],
      },
      {
        id: 13,
        name: 'Mushi',
        price: 790,
        cookTime: '25-34',
        favorite: false,
        origin: ['indian'],
        star:4.5,
        imageUrl:'/assets/Food-13.jpg', //'https://bombayfreshfish.com/wp-content/uploads/2022/10/Bombil-main.jpg',
        tags: ['River', 'fish'],
      },
      {
        id: 14,
        name: 'Big Makul',
        price: 490,
        cookTime: '25-34',
        favorite: false,
        origin: ['indian'],
        star:4.5,
        imageUrl:'/assets/Food-14.jpg', //'https://bombayfreshfish.com/wp-content/uploads/2022/10/Bombil-main.jpg',
        tags: ['River', 'fish'],
      },
      {
        id: 15,
        name: 'Lepa',
        price: 195,
        cookTime: '25-34',
        favorite: false,
        origin: ['indian'],
        star:4.5,
        imageUrl:'/assets/Food-15.jpg', //'https://bombayfreshfish.com/wp-content/uploads/2022/10/Bombil-main.jpg',
        tags: ['River', 'fish'],
      },
      {
        id: 16,
        name: 'Kuppa ',
        price: 600,
        cookTime: '25-34',
        favorite: false,
        origin: ['indian'],
        star:4.5,
        imageUrl:'/assets/Food-16.jpg', //'https://bombayfreshfish.com/wp-content/uploads/2022/10/Bombil-main.jpg',
        tags: ['River', 'fish'],
      },
    ]
  }
}
